### ISSUE TITLE
How to create something similar like this website.

### ISSUE THREAD

**Issue by ghost** [Ladysnake/Ladysnake.github.io#95]
Ok before I get bashed for this not being related to any "real issues", I just wanted to ask if the website design and stuff can be easily replicated. I assume that only the `public` folder is required for the base theme, since all the CSS is in there, but yeah. Is there any easy way to sort of "replicate" this website design?

**Comment by sschr15** [comment]
The site is largely built off [Bootstrap](https://getbootstrap.com/docs/5.3/getting-started/introduction/) with custom styling to fit Ladysnake. To see its original structure before Xiri and Pyro redid it with a better Jekyll setup, look through the commit history for those done en masse by me a couple years ago. At that time, it was primarily plain HTML.

**Comment by Xiribidus** [comment]
(Why in the world am I credited? It was all Pyro I swear)
